### ISSUE TITLE
Meso-ionic crash library prep

### ISSUE THREAD

**Issue by jproudfoot11** [healx/lig3dlens#12]
Very nice!

Meso-ionic compounds are crashing the "calculating physchem properties" of the library prep.
eg: O=C([N-]c1c[n+](N2CCOCC2)no1)C1CCCCC1

Also is there a way to read the library at this stage in .smi format rather than .sdf?

Thanks

**Comment by danodonovan** [comment]
Hello @jproudfoot11  - sorry for the delay, for the first part of your question

> Meso-ionic compounds are crashing the "calculating physchem properties" of the library prep.
eg: O=C([N-]c1c[n+](https://github.com/healx/lig3dlens/issues/N2CCOCC2)no1)C1CCCCC1

Mesoionic compounds should be supported, but in this instance we believe there may be a mistake in your SMILES formulation. However - we should provide the user with a more informative error message!

**Comment by bill-tatsis** [comment]
Following up Dan's reply, the correct smiles should be `O=C([N-]c1c**[n+]**no1)C1CCCCC1`. 
Furthermore, Lig3Dlens can indeed accept as input files in .smi format.  The file should contain first the SMILES of a compound and then its ID, separated by a comma. 
For example:
O=C([N-]c1c[n+]no1)C1CCCCC1, meso1

**Comment by jproudfoot11** [comment]
Thanks.  I was using the SMILES as provided by the library vendor.  I'll need to preprocess to make sure all are valid.
