### ISSUE TITLE
Allow use of predetermined reference ligand conformation

### ISSUE THREAD

**Issue by Evert-Homan** [healx/lig3dlens#18]
Hi,

Thank you for making this code publicly available. I just started to play with it. What I understand is that during the alignment step, conformers are generated for both the reference ligand and the library to screen. Would it be possible to add an option to skip this for the reference ligand? This is relevant one has a protein-bound conformation of a reference ligand, in such cases you would want to align the library to that particular conformation.

Best wishes/Evert

**Comment by bill-tatsis** [comment]
Hi Evert,

Thanks for your message.

We will try to implement this new feature [user inputs 3D conformations of the reference ligand and/or of the compound library] as soon as possible.

Regarding the 3D conformation of the reference molecule, it would be a good idea to check before running the VS campaign if the tool/package and its underlying force field can reproduce the conformation from a co-crystal x-ray structure or another experimental method and how close this conformation is to the "low-energy" conformations generated from the given tool.

**Comment by Evert-Homan** [comment]
Agreed, reproducing and assessing the relative conformational energy of a reference ligand would be useful.

BW/Evert

**Comment by bill-tatsis** [comment]
New feature Lig3DLens can work with input files that contain the 3D conformations for the reference compound and/or the compound library
`
lig3dlens-align --ref input_3D-reference_molecule_file --lib input_3D-library_file_name  --out output_SD_file`
